// Generated by the protocol buffer compiler.  DO NOT EDIT!

@class AndroidParameter;
@class DynamicResourceInfo;
@class DynamicResourceItem;
@class DynamicResourceRequest;
@class DynamicResourceResult;
@class ExtraData;
@class IOSParameter;

typedef NS_ENUM(SInt32, DynamicResourceBizType) {
  DynamicResourceBizTypeUnknown = 0,
  DynamicResourceBizTypeHotpatch = 1,
  DynamicResourceBizTypeBundle = 2,
  DynamicResourceBizTypeBirdnest = 3,
  DynamicResourceBizTypeNebula = 4,
  DynamicResourceBizTypeIosdynamic = 5,
  DynamicResourceBizTypeCmd = 6,
};

typedef NS_ENUM(SInt32, AndroidVmType) {
  AndroidVmTypeAll = 0,
  AndroidVmTypeArt = 1,
  AndroidVmTypeDalvik = 2,
  AndroidVmTypeLemur = 3,
  AndroidVmTypeAoc = 4,
};

@interface DynamicResourceResult : NSObject
@property (nonatomic)BOOL success;
@property (nonatomic,strong) NSString* message;
@property (nonatomic,strong) NSMutableArray * info;
@end

@interface DynamicResourceInfo : NSObject
@property (nonatomic)DynamicResourceBizType bizType;
@property (nonatomic)BOOL success;
@property (nonatomic,strong) NSString* message;
@property (nonatomic,strong) NSString* version;
@property (nonatomic)BOOL rollback;
@property (nonatomic,strong) NSMutableArray * item;
@end

@interface DynamicResourceItem : NSObject
@property (nonatomic,strong) NSString* resId;
@property (nonatomic,strong) NSString* resVersion;
@property (nonatomic,strong) NSString* resType;
@property (nonatomic,strong) NSString* fileMd5;
@property (nonatomic,strong) NSString* fileUrl;
@property (nonatomic,strong) NSString* fileContent;
@property (nonatomic)SInt32 resStatus;
@property (nonatomic,strong) NSMutableArray * resExtraData;
@property (nonatomic,strong) NSString* issueDesc;
@property (nonatomic)SInt32 lazyLoad;
@property (nonatomic,strong) NSString* frameworkId;
@property (nonatomic)SInt32 quickRun;
@property (nonatomic)SInt32 restartApp;
@end

@interface ExtraData : NSObject
@property (nonatomic,strong) NSString* key;
@property (nonatomic,strong) NSString* value;
@end

@interface DynamicResourceRequest : NSObject
@property (nonatomic,strong) NSString* productId;
@property (nonatomic,strong) NSString* productVersion;
@property (nonatomic,strong) NSString* clientId;
@property (nonatomic,strong) NSString* phoneBrand;
@property (nonatomic,strong) NSString* phoneModel;
@property (nonatomic,strong) NSString* userId;
@property (nonatomic,strong) NSString* extraInfo;
@property (nonatomic,strong) NSString* netType;
@property (nonatomic,strong) AndroidParameter* androidParam;
@property (nonatomic,strong) IOSParameter* iosParam;
@property (nonatomic,strong) NSString* dynamicResourceType;
@property (nonatomic,strong) NSMutableArray * cmdUuid;
@property (nonatomic,strong) NSString* utdid;
@end

@interface AndroidParameter : NSObject
@property (nonatomic)AndroidVmType vmType;
@property (nonatomic,strong) NSString* releaseVersion;
@property (nonatomic,strong) NSString* channel;
@property (nonatomic,strong) NSString* apiLevel;
@property (nonatomic,strong) NSString* bandageVersion;
@property (nonatomic,strong) NSString* bundleVersion;
@property (nonatomic,strong) NSString* birdnestVersion;
@property (nonatomic,strong) NSString* nebulaVersion;
@property (nonatomic,strong) NSString* issueDesc;
@end

@interface IOSParameter : NSObject
@property (nonatomic,strong) NSString* osVersion;
@property (nonatomic,strong) NSMutableArray * patchUuid;
@property (nonatomic,strong) NSString* birdnestVersion;
@property (nonatomic,strong) NSString* nebulaVersion;
@property (nonatomic,strong) NSString* bundleVersion;
@end

