// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <APProtocolBuffers/ProtocolBuffers.h>

@class UnionExtraData;
@class UnionResourceIdv;
@class UnionResourceInfo;
@class UnionResourceItem;
@class UnionResourceLimit;
@class UnionResourceParam;
@class UnionResourceRequest;
@class UnionResourceResult;

typedef NS_ENUM(SInt32, UnionPlatformType) {
  UnionPlatformTypeAndroid = 0,
  UnionPlatformTypeIos = 1,
};

typedef NS_ENUM(SInt32, UnionAndroidVmType) {
  UnionAndroidVmTypeAll = 0,
  UnionAndroidVmTypeArt = 1,
  UnionAndroidVmTypeDalvik = 2,
  UnionAndroidVmTypeLemur = 3,
  UnionAndroidVmTypeAoc = 4,
};

typedef NS_ENUM(SInt32, UnionResourceBizType) {
  UnionResourceBizTypeUnknown = 0,
  UnionResourceBizTypeHotpatch = 1,
  UnionResourceBizTypeBundle = 2,
  UnionResourceBizTypeBirdnest = 3,
  UnionResourceBizTypeNebula = 4,
  UnionResourceBizTypeIosdynamic = 5,
  UnionResourceBizTypeCmd = 6,
  UnionResourceBizTypeResource = 7,
};

typedef NS_ENUM(SInt32, UnionStoreType) {
  UnionStoreTypeSd = 0,
  UnionStoreTypeMem = 1,
};

typedef NS_ENUM(SInt32, UnionDownloadType) {
  UnionDownloadTypeCdn = 0,
  UnionDownloadTypeCloudid = 1,
};

@interface UnionResourceRequest : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasPlatform;
@property (readonly) BOOL hasProductId;
@property (readonly) BOOL hasProductVersion;
@property (readonly) BOOL hasReleaseVersion;
@property (readonly) BOOL hasUtdid;
@property (readonly) BOOL hasClientId;
@property (readonly) BOOL hasPhoneBrand;
@property (readonly) BOOL hasPhoneModel;
@property (readonly) BOOL hasVmType;
@property (readonly) BOOL hasChannel;
@property (readonly) BOOL hasApiLevel;
@property (readonly) BOOL hasOsVersion;
@property (readonly) BOOL hasNetType;
@property (readonly) BOOL hasExtraInfo;
@property (readonly) BOOL hasUid;
@property (readonly) BOOL hasManufacturer;
@property (nonatomic)UnionPlatformType platform;
@property (nonatomic,strong) NSString* productId;
@property (nonatomic,strong) NSString* productVersion;
@property (nonatomic,strong) NSString* releaseVersion;
@property (nonatomic,strong) NSString* utdid;
@property (nonatomic,strong) NSString* clientId;
@property (nonatomic,strong) NSString* phoneBrand;
@property (nonatomic,strong) NSString* phoneModel;
@property (nonatomic)UnionAndroidVmType vmType;
@property (nonatomic,strong) NSString* channel;
@property (nonatomic,strong) NSString* apiLevel;
@property (nonatomic,strong) NSString* osVersion;
@property (nonatomic,strong) NSString* netType;
@property (nonatomic,strong) NSString* extraInfo;
@property (nonatomic,strong) NSMutableArray * resourceParam;
@property (nonatomic,strong) NSString* uid;
@property (nonatomic,strong) NSMutableArray * cpuInstructionList;
@property (nonatomic,strong) NSString* manufacturer;
@end

@interface UnionResourceParam : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasBizType;
@property (readonly) BOOL hasUpdateVersion;
@property (readonly) BOOL hasIssueDesc;
@property (readonly) BOOL hasBusiness;
@property (nonatomic)UnionResourceBizType bizType;
@property (nonatomic,strong) NSMutableArray * uuid;
@property (nonatomic,strong) NSString* updateVersion;
@property (nonatomic,strong) NSString* issueDesc;
@property (nonatomic,strong) NSString* business;
@property (nonatomic,strong) NSMutableArray * resourceIdv;
@end

@interface UnionResourceIdv : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasResId;
@property (readonly) BOOL hasResVersion;
@property (nonatomic,strong) NSString* resId;
@property (nonatomic,strong) NSString* resVersion;
@end

@interface UnionResourceResult : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasSuccess;
@property (readonly) BOOL hasMessage;
@property (readonly) BOOL hasLimit;
@property (nonatomic)BOOL success;
@property (nonatomic,strong) NSString* message;
@property (nonatomic,strong) NSMutableArray * info;
@property (nonatomic,strong) UnionResourceLimit* limit;
@end

@interface UnionResourceLimit : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasWaittime;
@property (readonly) BOOL hasRandomtime;
@property (nonatomic)SInt32 waittime;
@property (nonatomic)SInt32 randomtime;
@end

@interface UnionResourceInfo : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasBizType;
@property (readonly) BOOL hasSuccess;
@property (readonly) BOOL hasMessage;
@property (readonly) BOOL hasVersion;
@property (readonly) BOOL hasRollback;
@property (readonly) BOOL hasQuickRollback;
@property (nonatomic)UnionResourceBizType bizType;
@property (nonatomic)BOOL success;
@property (nonatomic,strong) NSString* message;
@property (nonatomic,strong) NSString* version;
@property (nonatomic)BOOL rollback;
@property (nonatomic,strong) NSMutableArray * item;
@property (nonatomic)SInt32 quickRollback;
@end

@interface UnionResourceItem : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasResId;
@property (readonly) BOOL hasResVersion;
@property (readonly) BOOL hasResType;
@property (readonly) BOOL hasFileMd5;
@property (readonly) BOOL hasFileUrl;
@property (readonly) BOOL hasFileContent;
@property (readonly) BOOL hasBusiness;
@property (readonly) BOOL hasDownloadType;
@property (readonly) BOOL hasStoreType;
@property (readonly) BOOL hasResStatus;
@property (readonly) BOOL hasIssueDesc;
@property (readonly) BOOL hasLazyLoad;
@property (readonly) BOOL hasFileData;
@property (readonly) BOOL hasDiffMd5;
@property (readonly) BOOL hasDiffUrl;
@property (readonly) BOOL hasDiffContent;
@property (readonly) BOOL hasFrameworkId;
@property (readonly) BOOL hasQuickRun;
@property (readonly) BOOL hasRestartApp;
@property (nonatomic,strong) NSString* resId;
@property (nonatomic,strong) NSString* resVersion;
@property (nonatomic,strong) NSString* resType;
@property (nonatomic,strong) NSString* fileMd5;
@property (nonatomic,strong) NSString* fileUrl;
@property (nonatomic,strong) NSString* fileContent;
@property (nonatomic,strong) NSString* business;
@property (nonatomic)UnionDownloadType downloadType;
@property (nonatomic)UnionStoreType storeType;
@property (nonatomic)SInt32 resStatus;
@property (nonatomic,strong) NSMutableArray * resExtraData;
@property (nonatomic,strong) NSString* issueDesc;
@property (nonatomic)SInt32 lazyLoad;
@property (nonatomic,strong) NSData* fileData;
@property (nonatomic,strong) NSString* diffMd5;
@property (nonatomic,strong) NSString* diffUrl;
@property (nonatomic,strong) NSString* diffContent;
@property (nonatomic,strong) NSString* frameworkId;
@property (nonatomic)SInt32 quickRun;
@property (nonatomic)SInt32 restartApp;
@end

@interface UnionExtraData : APPBGeneratedMessage<GeneratedMessageProtocol>
@property (readonly) BOOL hasKey;
@property (readonly) BOOL hasValue;
@property (nonatomic,strong) NSString* key;
@property (nonatomic,strong) NSString* value;
@end

